### ISSUE TITLE
Is development still going for this repo?

### ISSUE THREAD

**Issue by ty-dev** [orbbec/astra#10]

**Comment by JoshBlake** [comment]
Yes, though for the last several months and the next our main efforts are focused on related capabilities that are not necessarily in this repo.

**Comment by ty-dev** [comment]
Ah okay thanks for the response. Anything that would be helpful for body scanning?

**Comment by JoshBlake** [comment]
Can't comment on anything in development yet. (To be clear when we fix/add stuff on the Astra SDK we'll usually push to github pretty immediately though.)
