### ISSUE TITLE
skeleton？？

### ISSUE THREAD

**Issue by zhaishengfu** [orbbec/astra#11]
hello， i compiled the simpleskeleton-sfml， but when i run it， the result is strange with not showing any skeleton at all！！what is the problem？？

**Comment by JoshBlake** [comment]
That sample is a stub for our skeleton tracker, which is not released yet.

**Comment by zhaishengfu** [comment]
My friend used the your SDK under android, and can show the skeleton perfectly! i compiled under linux. I am really strange why you can support android but can't support linux??

**Comment by JoshBlake** [comment]
There are several software libraries available for different scenarios, but this repository does not include a skeleton tracker. Please email info@orbbec3d.com for additional support. Thanks!
