### ISSUE TITLE
Invalid environment path is set by install.sh

### ISSUE THREAD

**Issue by harumo11** [orbbec/astra#18]
Hello and thanks for making good device and SDK.

I could not build Hello world program as below at Ubuntu 16.04.

```c++
//Hello world program

#include <astra/astra.hpp>

#include <cstdio>
#include <iostream>

int main(int argc, char** argv)
{
   std::cout << "hit enter to exit program" << std::endl;
   std::cin.get();

   return 0;
}
```

```cmake
#CMakeLists.txt for Hello world program

cmake_minimum_required(VERSION 3.5)

add_definitions("-std=c++11")

set(ENV{ASTRA_SDK_INCLUDE} ASTRA_SDK_INCLUDE)
set(ENV{ASTRA_SDK_LIB} ASTRA_SDK_LIB})

link_directories($ENV{ASTRA_SDK_INCLUDE})
include_directories($ENV{ASTRA_SDK_LIB})

add_executable(hello hello.cpp)
target_link_libraries(hello astra)
```
The reason is that the appropriate path was not set in my PC.
And then I find that install.sh(astra/install/install.sh)  tried to set not good path.

install.sh set paths as bellow(I put SDK in /home/robot/opt/).
```
 export ASTRA_SDK_INCLUDE=/home/robot/opt/astra/install/include
 export ASTRA_SDK_LIB=/home/robot/opt/astra/install/lib
```
But I think the paths is wrong. Because include and install directories  don't exist in
 /home/robot/opt/astra/install/ directory.
And valid one is as below.
```
 export ASTRA_SDK_INCLUDE=/home/robot/opt/astra/include
 export ASTRA_SDK_LIB=/home/robot/opt/astra/lib
```
How do you think?

Thanks in advance.

**Comment by JoshBlake** [comment]
Thanks for reporting this. I can see that the suggested export statements provided won't be correct. We will fix in the next release of the SDK. In the meantime, the work-around is to remove the extra install/ from the suggested path before copying to .bash_profile.

**Comment by harumo11** [comment]
Thank you. @JoshBlake 
I'm looking forward to the next release of the SDK.
