### ISSUE TITLE
How can I use it?

### ISSUE THREAD

**Issue by lanzhou2012** [orbbec/astra#19]
Sorry sir, but I want to know how can I use it? Do you have a demo or example about it? where can I get a instructions?

**Comment by JoshBlake** [comment]
There is a readme located in astra/samples-aux/README.txt. It gets dropped at the root of precompiled SDK distributions like you find at https://orbbec3d.com/develop/. If you need more than that, you might try asking at https://3dclub.orbbec3d.com/ or emailing info@orbbec3d.com.
