### ISSUE TITLE
Compile orbbec-sample (android) apk failed

### ISSUE THREAD

**Issue by blackerpaper** [orbbec/astra#5]
After ./gradlew build this error is shows up

`jni/SensorViewer/lit_depth_visualizer.hpp:31:28: error: 'from_cvector' is not a member of 'astra::vector3f'`
`jni/SensorViewer/AstraTest.h:75:16: error: 'astra::Astra' has not been declared
         astra::Astra::initialize();`

When i search `from_cvector` method, i cannot found it in anywhere in the source code. Don't know what it is.

Also cannot found `astra::Astra::initialize()` in the source code. Maybe it is `astra::initialize()`. If i change it to this, it triggered new error

`/Users/blacktoad/Documents/astra//include/astra_core/astra_core.hpp:32: error: undefined reference to 'astra_initialize'
collect2: error: ld returned 1 exit status`

How to fixed this?

**Comment by JoshBlake** [comment]
Sorry about that, Android test apps are a little out of date as we are fixing some things in preparation for v0.5. Keep an eye on develop this week.

**Comment by blackerpaper** [comment]
okay thank you for the response.
