### ISSUE TITLE
Some problem about the shared library

### ISSUE THREAD

**Issue by tryBetter** [orbbec/astra#9]
logcat : 
```
Process: com.orbbec.SkeletonViewer, PID: 4867 java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH in "libobp.jni.so" (built with --hash-style=gnu?)
```
Please tell me how to fix it , Thank you.

**Comment by JoshBlake** [comment]
I think this issue is for a different project. If you still have this problem, please contact info@orbbec3d.com for support.
